### ISSUE TITLE
Adding global Lustre filesystem prevents undeploy

### ISSUE THREAD

**Issue by behlendorf** [NearNodeFlash/NearNodeFlash.github.io#33] opened 2023-02-10 23:44 UTC
Creating a `lustrefilesystem.cray.hpe.com` resource prevents `nnf-deploy undeploy` from completing.

```
$ nnf-deploy deploy
$ kubectl apply -f ./lslide-dm.yaml
lustrefilesystem.cray.hpe.com/kern created
```

A subsequent undeploy will block indefinitely in `lustre-fs-operator`.  Removing the finalizer in `lustrefilesystem.cray.hpe.com` allows it to continue.

```
Undeploying Module lustre-fs-operator...
  Finding Overlay...
  Running Undeploy...
  <blocked>
```

**Comment by NateThornton** [comment] 2023-02-15 15:35
You need to ensure that all `lustrefilesystems` resources, like `workflow` resources, are all deleted prior to running undeploy. Otherwise, and as you observed, you risk the undeploy becoming stuck.

**Comment by NateThornton** [comment] 2023-02-15 15:41
Duplicate of https://github.com/NearNodeFlash/nnf-deploy/issues/32

**Comment by NateThornton** [comment] 2023-02-17 17:32
Please see the newly added [undeploy instructions](https://github.com/NearNodeFlash/nnf-deploy#undeploy). If you continue to have issues please re-open the ticket

**Closed by NateThornton** 2023-02-17 17:32 UTC
